switch v := data.(type) {
    case []interface{}:
        if len(v) > 0 {
            switch v[0].(type) {
            case string:
                ...
            case float64:
                ...
            case int64:
                ...
            case map[string]interface{}:
                ...
            }
        } else {
            ...
        }
    case []map[string]interface{}:
        ...
    case map[string]interface{}:
        ...
    default:
       ...
}
